#config_version=5
#
# Williams Hot Tip 
# Mission Pinball Framework Version .56 Aug 2023
# Author: Todd Legere
# To test virtual machine version start two terminal sesssions 
# 1) mpf both -X 
# 2) mpf monitor
# On the virtual monitor you will find virtual buttons for 
# Start, Coins, ShutdownPC, Service Coin door open, Service_enter, Service_esc, Service_down, Service_up
# See Operators manual in this folder for details
# An extra credit is awarded at end of game if score greater than replay score (See setting replay score) and credits
# 
# To execute component test (make sure you are in hot_tip folder)
# python3 -m unittest discover
#


hardware:
  platform: opp
  driverboards: gen2
# Identify Neosegment hardware 14segment display
  segment_displays: light_segment_displays
 
neoseg_displays:
  neoSeg_0:
    start_channel: 0-0-0
    size: 8digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_orange
  neoSeg_1:
    start_channel: 0-0-120
    size: 8digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_orange

  neoSeg_2:
    start_channel: 0-0-240
    size: 8digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_orange

  neoSeg_3:
    start_channel: 0-0-360
    size: 8digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_orange

  neoSeg_4:
    start_channel: 0-0-480
    size: 2digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_orange

  neoSeg_5:
    start_channel: 0-0-510
    size: 2digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_orange

light_settings:
  color_correction_profiles:
    NeoSeg_orange:
# For the brightest light set to .9 but I like between .5 to .7
      whitepoint: [.7, .7, .7]

segment_displays:
  neoSegTop:
    number: 1
    size: 16
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
         - neoSeg_0
         - neoSeg_1
      type: 14segment

  neoSegPlayer1:
    number: 1
    size: 8
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_0
      type: 14segment
  neoSegPlayer2:
    number: 2
    size: 8
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_1
      type: 14segment

  neoSegPlayer3:
    number: 3
    size: 8
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_2
      type: 14segment

  neoSegPlayer4:
    number: 4
    size: 8
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_3
      type: 14segment

  neoSegball:
    number: 5
    size: 2
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_4
      type: 14segment

  neoSegcredit:
    number: 5
    size: 2
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_5
      type: 14segment


segment_display_player:
  init_done:
    neoSegPlayer1:
      text: "HotTip"
      expire: 5s
      transition:
        type: push
        direction: right
        text: " *** "
      transition_out:
        type: push
        direction: right
        text: " *** "

opp:
# Turn debug off after slingshot debugged
#  debug: true
  ports: /dev/ttyACM0, /dev/ttyACM1

machine:
  balls_installed: 5
  min_balls: 1

virtual_platform_start_active_switches: s_outhole

mpf-mc:
  fps: 60

window:
  width: 800 
  height: 600
#  title: Mission Pinball Framework - HOT TIP
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: window

displays:
  window:
    width: 1200
    height: 1110
  dmd:
    width: 128
    height: 32
    default: true

sound_player:
  s_start_active: 1000_pts
  s_door_open_active: 1000_pts
  s_service_enter_active: 1000_pts
  s_service_up_active: 1000_pts
  s_service_down_active: 1000_pts
  s_shutdown_active: game_over
  s_coin_btn_active: coin_inserted
  s_right_coin_active: coin_inserted
  
drop_targets:
  left_drop1:
    switch: s_lbdrop1
    debug: True
  left_drop2:
    switch: s_lbdrop2
    debug: True
  left_drop3:
    switch: s_lbdrop3
    debug: True
  right_drop1:
    switch: s_rbdrop1
    debug: True
  right_drop2:
    switch: s_rbdrop2
    debug: True
  right_drop3:
    switch: s_rbdrop3
    debug: True

drop_target_banks:
  left_bank:
    drop_targets: left_drop1, left_drop2, left_drop3, right_drop1, right_drop2, right_drop3
    reset_coils: c_rbdropreset1, c_lbdropreset1
    # maximum drop target bank retry attempts (need to add to CE3K and Phoenix)
    max_reset_attempts: 2
    reset_events:
      ball_started
#      Allow targets to settle before poping up both banks
    reset_on_complete: 750ms  # Was 3s but it was too long

playfields:
  playfield:
    default_source_device: trough
    tags: default

ball_devices:
  trough:
    eject_coil: c_outhole
    ball_switches: s_outhole
    # Default timeout on failure to long shorten it to 2s
    eject_timeouts: 2s
    debug: true
    tags: trough, home, drain

# Using EOS Switch so no hold_coil required
flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    activation_switch: s_flipper_left
    enable_events: ball_started #machine_reset_phase_3 #For testing
    disable_events: ball_will_end, service_mode_entered
  right_flipper:
    main_coil: c_flipper_right_main
    activation_switch: s_flipper_right
    enable_events: ball_started #machine_reset_phase_3 
    disable_events: ball_will_end, service_mode_entered

slides:
  window_slide_1:
  - type: display
    width: 512
    height: 128
    anchor_y: bottom
    y: 5
    effects:
      - type: dmd
        dot_color: ff5500
        background_color: 220000
  - type: rectangle
    width: 514
    height: 130
    color: 444444
    anchor_y: bottom
    y: 5
  - type: image
    image: hottipbackglass
    anchor_y: top
    anchor_x: left
    y: top
    x: 0

  waiting_for_connection:
  - type: text
    text: WAITING FOR MPF CONNECTION

  asset_status:
  - type: text
    text: "LOADING ASSETS: (percent)%"

slide_player:
  init_done:
    window_slide_1:
      target: window
  loading_assets: asset_status

config:
- keyboard.yaml
- lights.yaml
- coils.yaml
- switches.yaml

smart_virtual:
  file_log: full

mpf:
  default_pulse_ms: 20

# Give cobrapin capacitors time to charge after firing flippers
psus:
  default:
    release_wait_ms: 50

modes:
- base
- attract
- bonus
- high_score
- tilt
- droptargets
- service
- credits
- match
- shoot_again
- shutdown_computer

player_vars:
# Turn off player name when high score
  initials:
    value_type: str
    initial_value: AAA
# My tilted warning
  my_tilted:
    initial_value: 0
# No replay at settings.replay_score_level1 awarded yet
  replay_level_1:
    initial_value: 0
# Used in shoot_again.yaml & set in base.yaml
  my_extraball_awarded:
    initial_value: 0
# Drop target value starts @ 10pts, after all dropped raises to 100 then 1000 see droptargets.yaml
  drop_value:
    initial_value: 10
# Spinner value Initial value 100 increases to 1,000 when 10,000 playfield bomus lamp lit
  spinner_value:
    initial_value: 10
# See mode/droptarget.yaml, Drop all 4 drop targets & increase multiplier. start value 1 to max 5
  my_multiplier:
    value_type: int
    initial_value: 1
  multiplier:
    value_type: int
    initial_value: 1
  bonus:
    value_type: int
    initial_value: 0
  captive_lamp_on:
    value_type: int
    initial_value: 0
  my_capball_awarded:
    value_type: int
    initial_value: 0
  my_dblbonus_awarded:
    value_type: int
    initial_value: 0

  double_lamp_on:
    value_type: int
    initial_value: 0
  eject1000_lamp_on:
    value_type: int
    initial_value: 0
# Turn on extra ball lamp when horseshoe2 lite give extra if leftouthole hit
  extraball_lamp_on:
    value_type: int
    initial_value: 0
# Turn on spinner lamp when horseshoe1 lamp on
  spinner_lamp_on:
    value_type: int
    initial_value: 0

# Used by service mode (Adjustments) replay score, # of balls, max_credits (settings), tilt warnings, tilt wait, tilt sensitivity
settings:
  warnings_to_tilt:
    label: Number of tilt warnings
    values:
      0: "no warnings"
      1: "1"
      2: "2"
      3: "3"
      5: "5"
      10: "10"
    default: 3
    key_type: int
    sort: 600
  settle_time:
    label: Time to wait on tilt to settle bob
    values:
      3000: "3s"
      5000: "5s"
      10000: "10s"
    default: 5000
    key_type: int
    sort: 610
  multiple_hit_window:
    label: Tilt sensitivity
    values:
      150: "sensitive"
      300: "normal"
      500: "insensitive"
      1000: "very insensitive"
    default: 300
    key_type: int
    sort: 620

  replay_score:
    label: Replay Score
    values:
      90000: "90000 (default)"
      140000: "140000"
      200000: "200000"
    default: 90000
    key_type: int
    sort: 100
  balls_per_game:
    label: Balls per game
    values:
      3: "3 (default)"
      5: "5"
    default: 3
    key_type: int
    sort: 100

# Used by credits.yaml
  max_credits:
    label: Max Credits
    values:
      10: "10"
      20: "20 (Default)"
    default: 20
    key_type: int
    sort: 100

# Service Menu (Adjustments) allows changing # balls per game 
game:
  balls_per_game: 3 if settings.balls_per_game==0 else settings.balls_per_game
  max_players: 4

# Service Menu (Adjustments) allows changing credits 
credits:
  max_credits: 20 if settings.max_credits==0 else settings.max_credits
# Set To coins required. Change free_play: true for Free play (I prefer adding coins)
  free_play: false
  price_tier_template: "{{credits}} CREDITS ${{price}}"
# Give free credit by pressing s_service_esc switch
  service_credits_switch: s_coin_btn
  switches:
    - switch: s_left_coin
      type: dollars
      value: 1
    - switch: s_right_coin
      type: dollars
      value: 1
    - switch: s_coin_btn
      type: dollars
      value: 1
  pricing_tiers:
    - price: 1
      credits: 1
  free_play_string: FREE PLAY
  credits_string: CREDIT

  events:
    - event: add_credit
      type: award
      credits: 1
    - event: match_has_match
      type: award
      credits: winners
    - event: special
      type: special
      credits: 1
    - event: game_ending{current_player.score > settings.replay_score}
      type: award
      credits: 1
    - event: high_score_credit
      type: high_score
      credits: 1
    - event: match
      type: match
      credits: 1
  fractional_credit_expiration_time: 15m
  credit_expiration_time: 2h
  persist_credits_while_off_time: 1h

widget_styles:
  text_default:
    font_name: Quadrit
    font_size: 10
    adjust_top: 2
    adjust_bottom: 3
  space_title_huge:
    font_name: DEADJIM
    font_size: 29
    antialias: true
    adjust_top: 3
    adjust_bottom: 3
  space_title:
    font_name: DEADJIM
    font_size: 21
    antialias: true
    adjust_top: 2
    adjust_bottom: 3
  medium:
    font_name: pixelmix
    font_size: 8
    adjust_top: 1
    adjust_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 9
    adjust_top: 2
    adjust_bottom: 3
  tall_title:
    font_name: big_noodle_titling
    font_size: 20

#
# Sound settings
#
sound_system:
  tracks:
    voice:
      volume: 1
      priorsounity: 2
      simultaneous_sounds: 1
      preload: true
    sfx:
      volume: 1
      priority: 1
      preload: true
      simultaneous_sounds: 7
    music:
      volume: 0.7
      simultaneous_sounds: 1
  buffer: 2048  # previous value was 512
  frequency: 44100
  channels: 1
  master_volume: 1
  enabled: true

sound_pools:
  bulls_eye_pool:
    type: random
    track: sfx
    sounds:
      - ThatsGottaHurt
      - ShitHappens
      - YourFucked
      - YourFaceYourAssWhatsTheDiff
      - ShitDownYourNeck
      - PantiesInABunch
      - MyNamesDukeNukem
      - KillYouOldStyle
      - KickYourAssBitch
      
assets:
  sounds:
    default:
      track: sfx
    music:
      track: music
    sfx:
      track: sfx
    voice:
      track: voice
