#config_version=5

event_player:
  player_added: chime_test_show

show_player:
# Don't add this attract_display_loop in
#  mode_attract_started: attract_display_loop
  credits_added:
    attract_7seg_loop: stop
    my_credits_show:
      loops: 2
      speed: 1
  not_enough_credits:
    attract_7seg_loop: stop
    my_credits_show:
      loops: 2
      speed: 1
  player_added:
    attract_7seg_loop: stop
    my_playeradded_show:
      loops: 2
      speed: 1

shows:
  attract_display_loop:
    - duration: 2s
      slides:
        press_start:
          target: dmd
          widgets:
            - type: Text
              text: PRESS START
          transition:
            type: move_in
            duration: 1s
            direction: top
    - duration: 2s
      slides:
        credits_slide:
          target: dmd
          widgets:
            - type: text
              text: (machine|credits_string)
          transition:
            type: move_in
            duration: 1s
            direction: bottom

slide_player:
  credits_added:
    credit_added_slide:
      expire: 2s
  not_enough_credits:
    not_enough_credits_slide:
      expire: 2s
  enabling_free_play:
    enabling_free_play_slide:
      expire: 2s
  enabling_credit_play:
    enabling_credit_play_slide:
      expire: 2s
  max_credits_reached:
    max_credits_reached_slide:
      expire: 2s
  player_added:
    player_added_slide:
      expire: 1s
slides:
  credit_added_slide:
    - type: text
      text: (machine|credits_string)
  not_enough_credits_slide:
    - type: text
      text: (machine|credits_string)
      font_size: 10
      anchor_y: top
    - type: text
      text: INSERT COINS
      font_size: 10
      anchor_y: bottom
  enabling_free_play_slide:
    - type: text
      text: ENABLING FREE PLAY
  enabling_credit_play_slide:
    - type: text
      text: ENABLING CREDIT PLAY
    - type: text
      text: (machine|credits_string)
  max_credits_reached_slide:
    - type: text
      text: MAX CREDITS REACHED
  player_added_slide:
    - type: text
      text: PLAYER ADDED
      font_size: 12
      color: white
sound_player:
  credits_added:
#    credit_added_sound:
    coin_inserted:
      action: play
      loops: 0
  not_enough_credits:
    doh:
      action: play
      loops: 0
  player_added:
    payback_time:
      action: play
      loops: 0
